using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace QubicaCinema.BuildingBlocks.Persistence.Outbox;

/// <summary>Maps <see cref="OutboxMessage"/> to the <c>OutboxMessages</c> table.</summary>
internal sealed class OutboxMessageConfiguration : IEntityTypeConfiguration<OutboxMessage>
{
    /// <summary>The table's name, shared with the raw SQL that claims a batch.</summary>
    internal const string TableName = "OutboxMessages";

    /// <summary>The index the publisher reads through.</summary>
    internal const string UnprocessedIndexName = "IX_OutboxMessages_Unprocessed";

    public void Configure(EntityTypeBuilder<OutboxMessage> builder)
    {
        builder.ToTable(TableName);
        builder.HasKey(message => message.Id);

        // The event's own id, never generated by the database.
        builder.Property(message => message.Id).ValueGeneratedNever();

        builder.Property(message => message.EventName).HasMaxLength(200).IsRequired();
        builder.Property(message => message.Payload).IsRequired();
        builder.Property(message => message.OccurredAt).IsRequired();

        // A W3C traceparent is exactly 55 characters; tracestate is bounded at 512 by the specification.
        builder.Property(message => message.TraceParent).HasMaxLength(55);
        builder.Property(message => message.TraceState).HasMaxLength(512);

        builder.Property(message => message.LastError).HasMaxLength(OutboxMessage.MaxErrorLength);

        // Only unpublished rows are ever read, and they are a handful next to the table's history. A filtered
        // index keeps the publisher's query cheap however many published rows pile up.
        builder.HasIndex(message => new { message.OccurredAt, message.Id }, UnprocessedIndexName)
            .HasFilter("[ProcessedAt] IS NULL");
    }
}
